title: Pandora
subtitle: "pandora 组件"
description: "pandora 组件"
author: lynzz
timezone: UTC
language: zh-cn
url: https://pandorajs.github.io
root: /
permalink: blog/:year/:month/:day/:title/
archive_dir: blog
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:pandorajs/pandorajs.github.io.git

duoshuo_shortname: pandorajs
github: lynzz
